/* H3L · textos de la consulta en lenguaje natural y la vigilancia de anomalías (es, en, fr, pt).
   Incluye los documentos de demostración, las palabras clave de interpretación y las preguntas sugeridas.
   Desarrollado por Leandro Collell. */
(function(){'use strict';
var o={es:{},en:{},fr:{},pt:{}};
function A(k,es,en,fr,pt){o.es[k]=es;o.en[k]=en;o.fr[k]=fr;o.pt[k]=pt}
function D(id,es,en,fr,pt){[['es',es],['en',en],['fr',fr],['pt',pt]].forEach(function(p){var v=p[1],l=p[0];o[l]['doc.'+id+'.t']=v[0];o[l]['doc.'+id+'.x']=v[1];if(v[2])o[l]['doc.'+id+'.a']=v[2]})}

/* ---- sección ---- */
A('a.t',"Pregunte en sus palabras y el tablero se arma solo.","Ask in your own words and the board builds itself.","Posez votre question avec vos mots et le tableau se construit seul.","Pergunte com suas palavras e o painel se monta sozinho.");
A('a.lede',"Escriba lo que quiere verificar. Un equipo de agentes busca en la documentación, calcula con los datos y dibuja los gráficos que hacen falta para responder.","Type what you want to check. A team of agents searches the documentation, calculates with the data and draws the charts needed to answer.","Écrivez ce que vous voulez vérifier. Une équipe d’agents cherche dans la documentation, calcule avec les données et dessine les graphiques nécessaires pour répondre.","Escreva o que quer verificar. Uma equipe de agentes busca na documentação, calcula com os dados e desenha os gráficos necessários para responder.");
A('a.lbl',"Su consulta","Your question","Votre question","Sua pergunta");
A('a.ph',"Ej.: ¿Por qué bajó la producción de Costa?","E.g.: Why did production drop in Coast?","Ex. : Pourquoi la production de Côte a-t-elle baissé ?","Ex.: Por que a produção de Costa caiu?");
A('a.btn',"Armar tablero","Build board","Construire le tableau","Montar painel");
A('a.ch1',"¿Por qué bajó la producción de Costa?","Why did production drop in Coast?","Pourquoi la production de Côte a-t-elle baissé ?","Por que a produção de Costa caiu?");
A('a.ch2',"Costos de Valle de los últimos 3 meses","Costs for Valley over the last 3 months","Coûts de Vallée sur les 3 derniers mois","Custos de Vale nos últimos 3 meses");
A('a.ch3',"Emisiones por campo, últimos 3 meses","Emissions by field, last 3 months","Émissions par champ, 3 derniers mois","Emissões por campo, últimos 3 meses");
A('a.ch4',"Compará la producción de Norte y Sur","Compare production of North and South","Compare la production de Nord et Sud","Compare a produção de Norte e Sul");
A('a.ch5',"¿Dónde hay anomalías?","Where are the anomalies?","Où y a-t-il des anomalies ?","Onde há anomalias?");
A('a.ch6',"¿Qué reservas puedo reportar?","Which reserves can I report?","Quelles réserves puis-je déclarer ?","Quais reservas posso reportar?");

/* ---- vigilancia ---- */
A('a.wt',"Vigilancia automática","Automatic monitoring","Surveillance automatique","Vigilância automática");
A('a.ws',"El Vigía revisa producción, costos y emisiones de los cinco campos cada vez que entran datos.","The Watcher reviews production, costs and emissions of the five fields every time new data arrives.","La Vigie examine la production, les coûts et les émissions des cinq champs à chaque arrivée de données.","O Vigia revisa produção, custos e emissões dos cinco campos cada vez que entram dados.");
A('a.wok',"Sin anomalías en los últimos datos.","No anomalies in the latest data.","Aucune anomalie dans les dernières données.","Sem anomalias nos últimos dados.");
A('a.wi',"<b>{m} · {f}</b>: {p} contra lo esperado<small>Desde {d} · impacto estimado {i} mil USD/mes</small>","<b>{m} · {f}</b>: {p} versus expected<small>Since {d} · estimated impact {i} k USD/month</small>","<b>{m} · {f}</b> : {p} par rapport à l’attendu<small>Depuis {d} · impact estimé {i} k USD/mois</small>","<b>{m} · {f}</b>: {p} em relação ao esperado<small>Desde {d} · impacto estimado {i} mil USD/mês</small>");
A('a.wgo',"Abrir tablero","Open board","Ouvrir le tableau","Abrir painel");

/* ---- métricas ---- */
A('a.m.prod.nm',"producción","production","production","produção");
A('a.m.prod.Nm',"Producción","Production","Production","Produção");
A('a.m.prod.u',"bopd","bopd","bopd","bopd");
A('a.m.opex.nm',"costo operativo","operating cost","coût d’exploitation","custo operacional");
A('a.m.opex.Nm',"Costo operativo","Operating cost","Coût d’exploitation","Custo operacional");
A('a.m.opex.u',"MM USD/mes","MM USD/month","M USD/mois","MM USD/mês");
A('a.m.emis.nm',"emisiones","emissions","émissions","emissões");
A('a.m.emis.Nm',"Emisiones","Emissions","Émissions","Emissões");
A('a.m.emis.u',"kt CO₂e/mes","kt CO₂e/month","kt CO₂e/mois","kt CO₂e/mês");
A('a.all',"Todos los campos","All fields","Tous les champs","Todos os campos");
A('a.u.days',"días","days","jours","dias");
A('a.u.month',"mes","month","mois","mês");
A('a.u.months',"meses","months","mois","meses");
A('a.kusd',"mil USD","k USD","k USD","mil USD");
A('a.kusdm',"mil USD/mes","k USD/month","k USD/mois","mil USD/mês");

/* ---- interpretación: expresiones regulares sobre texto en minúsculas y sin acentos ---- */
A('a.re.emis',"emision|co2|co₂|venteo|quema|carbono|flaring|metano","emission|co2|co₂|venting|flaring|carbon|methane","emission|co2|co₂|event|torch|carbone|methane","emiss|co2|co₂|ventilac|queima|carbono|metano");
A('a.re.opex',"costo|gasto|opex|lifting|presupuesto operativo|energia|contrato","cost|spend|opex|lifting|operating budget|energy|power|contract","cout|depense|opex|lifting|budget d.exploitation|energie|contrat","custo|gasto|opex|lifting|orcamento operacional|energia|contrato");
A('a.re.prod',"produc|barril|bopd|caudal|pozo|cayo|bajo la prod","produc|barrel|bopd|output|\\bwells?\\b|dropped|fell","produc|baril|bopd|debit|puits|chute|baisse","produc|barril|bopd|vazao|poco|caiu|queda");
A('a.re.diag',"por que|porque|causa|anomal|problema|cayo|bajo|subio|aumento|desvio|raro|que paso|alerta","\\bwhy\\b|cause|anomal|problem|drop|fell|\\bfall|rise|rose|increase|deviat|strange|what happened|alert","pourquoi|cause|anomal|probleme|chute|baisse|hausse|augment|ecart|etrange|s.est passe|alerte","por que|porque|causa|anomal|problema|caiu|queda|subiu|aumento|desvio|estranho|o que aconteceu|alerta");
A('a.re.cmp',"compar|versus|contra| vs ","compar|versus|against| vs ","compar|versus|contre| vs ","compar|versus|contra| vs ");
A('a.re.scan',"anomal|alerta|vigilancia|donde hay|que esta mal","anomal|alert|monitor|where is|where are|what is wrong","anomal|alerte|surveillance|ou y a|ou sont|ne va pas","anomal|alerta|vigilancia|onde ha|o que esta errado");
A('a.re.res',"reserva|1p|2p|3p|contingente|prms","reserve|1p|2p|3p|contingent|prms","reserve|1p|2p|3p|contingent|prms","reserva|1p|2p|3p|contingente|prms");
A('a.re.inv',"proyecto|inversion|vpn|vpi|capex|brent|financiar","project|investment|npv|capex|brent|fund","projet|investissement|\\bvan\\b|capex|brent|financer","projeto|investimento|vpl|capex|brent|financiar");
A('a.re.num',"(\\d+)\\s*(dia|semana|mes)","(\\d+)\\s*(day|week|month)","(\\d+)\\s*(jour|semaine|mois)","(\\d+)\\s*(dia|semana|mes)");
A('a.unitw',"dia|semana|mes","day|week|month","jour|semaine|mois","dia|semana|mes");
A('a.stop',"de la el los las un una que en y o por para con del al se es a lo su sus mas hay como cuanto cual cuales","the a an of in on at for to and or is are was were what which how by with from as it its this that","de la le les un une des du et ou en pour par avec au aux est sont que qui quel quelle a ce cet cette son sa ses sur dans","de a o os as um uma que em e ou por para com do da dos das ao se e eh seu sua mais ha como quanto qual quais");

/* ---- tablero armado ---- */
A('a.tag.auto',"Armado automáticamente por el Vigía","Built automatically by the Watcher","Construit automatiquement par la Vigie","Montado automaticamente pelo Vigia");
A('a.tag.user',"Armado a su consulta","Built for your question","Construit pour votre question","Montado para a sua pergunta");
A('a.under',"Entendí: <b>{m}</b> · <b>{f}</b> · <b>últimos {n} {u}</b> · <b>{mode}</b>","I understood: <b>{m}</b> · <b>{f}</b> · <b>last {n} {u}</b> · <b>{mode}</b>","J’ai compris : <b>{m}</b> · <b>{f}</b> · <b>{n} derniers {u}</b> · <b>{mode}</b>","Entendi: <b>{m}</b> · <b>{f}</b> · <b>últimos {n} {u}</b> · <b>{mode}</b>");
A('a.mode.auto',"diagnóstico de anomalía","anomaly diagnosis","diagnostic d’anomalie","diagnóstico de anomalia");
A('a.mode.compare',"comparación","comparison","comparaison","comparação");
A('a.mode.diag',"diagnóstico","diagnosis","diagnostic","diagnóstico");
A('a.mode.trend',"tendencia","trend","tendance","tendência");
A('a.stepsAria',"Pasos de los agentes","Agent steps","Étapes des agents","Passos dos agentes");
A('a.working',"Trabajando…","Working…","En cours…","Trabalhando…");
A('a.ag.orq',"Orquestador","Orchestrator","Orchestrateur","Orquestrador");
A('a.ag.rec',"Recuperador","Retriever","Récupérateur","Recuperador");
A('a.s1',"Interpreté la consulta y elegí <b>{m}</b> de <b>{f}</b> como tema. Asigné la búsqueda, el cálculo y la revisión.","I interpreted the question and picked <b>{m}</b> of <b>{f}</b> as the topic. I assigned the search, the calculation and the review.","J’ai interprété la question et retenu <b>{m}</b> de <b>{f}</b> comme sujet. J’ai confié la recherche, le calcul et la vérification.","Interpretei a pergunta e escolhi <b>{m}</b> de <b>{f}</b> como tema. Atribuí a busca, o cálculo e a revisão.");
A('a.s1s',"Reglas de interpretación y campos conocidos.","Interpretation rules and known fields.","Règles d’interprétation et champs connus.","Regras de interpretação e campos conhecidos.");
A('a.s2',"Busqué en {n} documentos y recuperé {h} pasajes: {ids}.","I searched {n} documents and retrieved {h} passages: {ids}.","J’ai cherché dans {n} documents et récupéré {h} passages : {ids}.","Busquei em {n} documentos e recuperei {h} trechos: {ids}.");
A('a.s2s',"Búsqueda por relevancia (BM25) sobre documentos de demostración.","Relevance search (BM25) over demo documents.","Recherche par pertinence (BM25) sur des documents de démonstration.","Busca por relevância (BM25) sobre documentos de demonstração.");
A('a.s3',"Ajusté la tendencia con {n} {u} previos y comparé los últimos {k}: desvío de <b>{z} σ</b>{tail}","I fitted the trend on the previous {n} {u} and compared the last {k}: deviation of <b>{z} σ</b>{tail}","J’ai ajusté la tendance sur {n} {u} précédents et comparé les {k} derniers : écart de <b>{z} σ</b>{tail}","Ajustei a tendência com {n} {u} anteriores e comparei os últimos {k}: desvio de <b>{z} σ</b>{tail}");
A('a.s3t',", con inicio el {d}.",", starting on {d}.",", à partir de {d}.",", com início em {d}.");
A('a.s3b',"Comparé los campos pedidos en el mismo período.","I compared the requested fields over the same period.","J’ai comparé les champs demandés sur la même période.","Comparei os campos pedidos no mesmo período.");
A('a.s3s',"Regresión sobre {w}; anomalía si el desvío adverso supera {l} σ.","Regression on {w}; anomaly if the adverse deviation exceeds {l} σ.","Régression sur {w} ; anomalie si l’écart défavorable dépasse {l} σ.","Regressão sobre {w}; anomalia se o desvio adverso superar {l} σ.");
A('a.s3w1',"el logaritmo de la producción","the logarithm of production","le logarithme de la production","o logaritmo da produção");
A('a.s3w2',"la serie mensual","the monthly series","la série mensuelle","a série mensal");
A('a.s4',"Controlé los datos: serie completa, sin faltantes ni valores fuera de rango{tail}","I checked the data: complete series, no gaps or out-of-range values{tail}","J’ai contrôlé les données : série complète, sans manque ni valeur hors plage{tail}","Conferi os dados: série completa, sem faltas nem valores fora de faixa{tail}");
A('a.s4t',"; el desvío persiste <b>{p} {u}</b>, no es un dato aislado.","; the deviation persists for <b>{p} {u}</b>, it is not an isolated reading.","; l’écart persiste <b>{p} {u}</b>, ce n’est pas une donnée isolée.","; o desvio persiste por <b>{p} {u}</b>, não é um dado isolado.");
A('a.s4s',"Regla aplicada: un desvío cuenta solo si se mantiene varios períodos.","Rule applied: a deviation counts only if it holds for several periods.","Règle appliquée : un écart ne compte que s’il se maintient sur plusieurs périodes.","Regra aplicada: um desvio só conta se se mantiver por vários períodos.");
A('a.s5',"Armé {n} gráficos, la lectura integrada y la recomendación con sus fuentes. Falta la aprobación de una persona.","I built {n} charts, the integrated reading and the recommendation with its sources. A person’s approval is still missing.","J’ai construit {n} graphiques, la lecture intégrée et la recommandation avec ses sources. L’approbation d’une personne manque encore.","Montei {n} gráficos, a leitura integrada e a recomendação com suas fontes. Falta a aprovação de uma pessoa.");
A('a.s5s',"Registro: fecha, datos, fuentes y versión del cálculo.","Record: date, data, sources and calculation version.","Registre : date, données, sources et version du calcul.","Registro: data, dados, fontes e versão do cálculo.");

/* ---- gráficos ---- */
A('a.c1t',"{Nm} de {f}: real contra esperado","{Nm} of {f}: actual versus expected","{Nm} de {f} : réel et attendu","{Nm} de {f}: real contra esperado");
A('a.c1sD',"Últimos {w} días. {u}. La banda es el rango esperado según la tendencia previa.","Last {w} days. {u}. The band is the expected range based on the previous trend.","{w} derniers jours. {u}. La bande est la plage attendue selon la tendance précédente.","Últimos {w} dias. {u}. A faixa é o intervalo esperado conforme a tendência anterior.");
A('a.c1sM',"Últimos 12 meses. {u}. La banda es el rango esperado según la tendencia previa.","Last 12 months. {u}. The band is the expected range based on the previous trend.","12 derniers mois. {u}. La bande est la plage attendue selon la tendance précédente.","Últimos 12 meses. {u}. A faixa é o intervalo esperado conforme a tendência anterior.");
A('a.exp',"Esperado","Expected","Attendu","Esperado");
A('a.band2',"Rango esperado (±2σ)","Expected range (±2σ)","Plage attendue (±2σ)","Intervalo esperado (±2σ)");
A('a.band',"Rango esperado","Expected range","Plage attendue","Intervalo esperado");
A('a.start',"Inicio del desvío","Deviation start","Début de l’écart","Início do desvio");
A('a.date',"Fecha","Date","Date","Data");
A('a.c2t',"Qué campos cambiaron","Which fields changed","Quels champs ont changé","Quais campos mudaram");
A('a.c2s',"Variación de los últimos {n} {u} contra los {n} anteriores. Naranja: cambio adverso fuera de lo esperado.","Change over the last {n} {u} against the previous {n}. Orange: adverse change outside what is expected.","Variation des {n} derniers {u} par rapport aux {n} précédents. Orange : changement défavorable hors de l’attendu.","Variação dos últimos {n} {u} contra os {n} anteriores. Laranja: mudança adversa fora do esperado.");
A('a.adv',"Adverso y fuera de lo esperado","Adverse and outside expected","Défavorable et hors de l’attendu","Adverso e fora do esperado");
A('a.inr',"Dentro de lo esperado","Within expected","Dans l’attendu","Dentro do esperado");
A('a.now',"Ahora","Now","Maintenant","Agora");
A('a.bef',"Antes","Before","Avant","Antes");
A('a.devx',"Desvío vs esperado","Deviation vs expected","Écart par rapport à l’attendu","Desvio vs esperado");
A('a.chg',"Variación","Change","Variation","Variação");
A('a.t2h',"Campo|Ahora|Antes|Variación","Field|Now|Before|Change","Champ|Maintenant|Avant|Variation","Campo|Agora|Antes|Variação");
A('a.c3wt',"Qué pozos explican la caída en {f}","Which wells explain the drop in {f}","Quels puits expliquent la chute à {f}","Quais poços explicam a queda em {f}");
A('a.c3ws',"bopd perdidos por pozo, comparando antes y después del desvío.","bopd lost per well, comparing before and after the deviation.","bopd perdus par puits, avant et après l’écart.","bopd perdidos por poço, comparando antes e depois do desvio.");
A('a.c3wl1',"Pozo con caída","Well with a drop","Puits en baisse","Poço com queda");
A('a.c3wl2',"Sin cambio","No change","Sans changement","Sem mudança");
A('a.c3wlost',"−{x} bopd","−{x} bopd","−{x} bopd","−{x} bopd");
A('a.c3wno',"sin cambio","no change","sans changement","sem mudança");
A('a.c3wh',"Pozo|Antes (bopd)|Ahora (bopd)","Well|Before (bopd)|Now (bopd)","Puits|Avant (bopd)|Maintenant (bopd)","Poço|Antes (bopd)|Agora (bopd)");
A('a.c3it',"Cuánto cuesta cada desvío","What each deviation costs","Ce que coûte chaque écart","Quanto custa cada desvio");
A('a.c3is',"Impacto estimado, en miles de USD por mes. Donde no hay desvío, cero.","Estimated impact, in thousands of USD per month. Where there is no deviation, zero.","Impact estimé, en milliers d’USD par mois. Là où il n’y a pas d’écart, zéro.","Impacto estimado, em milhares de USD por mês. Onde não há desvio, zero.");
A('a.c3il1',"Con desvío","With deviation","Avec écart","Com desvio");
A('a.c3il2',"Sin desvío","No deviation","Sans écart","Sem desvio");
A('a.c3itx',"{x} mil USD","{x} k USD","{x} k USD","{x} mil USD");
A('a.c3ino',"sin desvío","no deviation","sans écart","sem desvio");
A('a.c3iimp',"Impacto estimado","Estimated impact","Impact estimé","Impacto estimado");
A('a.c3ih',"Campo|Impacto (mil USD/mes)","Field|Impact (k USD/month)","Champ|Impact (k USD/mois)","Campo|Impacto (mil USD/mês)");

/* ---- indicadores ---- */
A('a.k1',"{Nm} de {f}","{Nm} of {f}","{Nm} de {f}","{Nm} de {f}");
A('a.k1d1',"Promedio de los últimos 7 días","Average of the last 7 days","Moyenne des 7 derniers jours","Média dos últimos 7 dias");
A('a.k1d2',"Último mes cerrado","Last closed month","Dernier mois clôturé","Último mês fechado");
A('a.k2',"Cambio contra el período previo","Change against the previous period","Variation par rapport à la période précédente","Mudança em relação ao período anterior");
A('a.k2d',"Últimos {n} {u} contra los {n} anteriores","Last {n} {u} against the previous {n}","{n} derniers {u} contre les {n} précédents","Últimos {n} {u} contra os {n} anteriores");
A('a.k3',"Desvío contra lo esperado","Deviation from expected","Écart par rapport à l’attendu","Desvio em relação ao esperado");
A('a.k3a',"<span class=\"bad\">Fuera de lo esperado</span> (límite: {l} σ)","<span class=\"bad\">Outside expected</span> (limit: {l} σ)","<span class=\"bad\">Hors de l’attendu</span> (limite : {l} σ)","<span class=\"bad\">Fora do esperado</span> (limite: {l} σ)");
A('a.k3b',"Dentro de lo esperado","Within expected","Dans l’attendu","Dentro do esperado");
A('a.k4',"Impacto estimado","Estimated impact","Impact estimé","Impacto estimado");
A('a.k4a',"Desde hace {p} {u}","For {p} {u}","Depuis {p} {u}","Há {p} {u}");
A('a.k4b',"Sin anomalía en este campo","No anomaly in this field","Aucune anomalie sur ce champ","Sem anomalia neste campo");

/* ---- lectura integrada ---- */
A('a.r1a',"En {nm} de <b>{f}</b> el valor real está <b>{p}</b> respecto de lo esperado desde <b>{d}</b>. El desvío ya dura <b>{pp} {u}</b> y no se explica por la declinación natural.","For {nm} at <b>{f}</b> the actual value is <b>{p}</b> versus expected since <b>{d}</b>. The deviation has lasted <b>{pp} {u}</b> and is not explained by natural decline.","Pour {nm} à <b>{f}</b>, la valeur réelle est <b>{p}</b> par rapport à l’attendu depuis <b>{d}</b>. L’écart dure depuis <b>{pp} {u}</b> et ne s’explique pas par le déclin naturel.","Em {nm} de <b>{f}</b> o valor real está <b>{p}</b> em relação ao esperado desde <b>{d}</b>. O desvio já dura <b>{pp} {u}</b> e não se explica pelo declínio natural.");
A('a.r1b',"En {nm} de <b>{f}</b> el valor real sigue la tendencia esperada: el desvío actual es de <b>{z} σ</b>, dentro del rango normal.","For {nm} at <b>{f}</b> the actual value follows the expected trend: the current deviation is <b>{z} σ</b>, within the normal range.","Pour {nm} à <b>{f}</b>, la valeur réelle suit la tendance attendue : l’écart actuel est de <b>{z} σ</b>, dans la plage normale.","Em {nm} de <b>{f}</b> o valor real segue a tendência esperada: o desvio atual é de <b>{z} σ</b>, dentro da faixa normal.");
A('a.r1c',"Se comparan <b>{list}</b> en el mismo período.","<b>{list}</b> are compared over the same period.","On compare <b>{list}</b> sur la même période.","Comparam-se <b>{list}</b> no mesmo período.");
A('a.r2a',"El cambio se concentra en <b>{list}</b>. {rest}","The change is concentrated in <b>{list}</b>. {rest}","Le changement se concentre sur <b>{list}</b>. {rest}","A mudança se concentra em <b>{list}</b>. {rest}");
A('a.r2r',"Los otros {n} campos se mantienen dentro de lo esperado.","The other {n} fields stay within what is expected.","Les {n} autres champs restent dans l’attendu.","Os outros {n} campos ficam dentro do esperado.");
A('a.r2b',"Ningún campo muestra un desvío fuera de lo esperado en {nm}. El mayor cambio es <b>{f} ({p})</b>.","No field shows a deviation outside what is expected in {nm}. The biggest change is <b>{f} ({p})</b>.","Aucun champ ne montre d’écart hors de l’attendu pour {nm}. Le plus grand changement est <b>{f} ({p})</b>.","Nenhum campo mostra desvio fora do esperado em {nm}. A maior mudança é <b>{f} ({p})</b>.");
A('a.r3a',"<b>{n} pozos</b> ({ids}) explican <b>{pc}</b> de la caída: <b>{l} bopd</b> menos que antes. El resto de los pozos del campo no cambió.","<b>{n} wells</b> ({ids}) explain <b>{pc}</b> of the drop: <b>{l} bopd</b> less than before. The rest of the field’s wells did not change.","<b>{n} puits</b> ({ids}) expliquent <b>{pc}</b> de la chute : <b>{l} bopd</b> de moins qu’avant. Les autres puits du champ n’ont pas changé.","<b>{n} poços</b> ({ids}) explicam <b>{pc}</b> da queda: <b>{l} bopd</b> a menos que antes. Os demais poços do campo não mudaram.");
A('a.r3b',"El impacto estimado es de <b>{i} mil USD por mes</b> ({how}).","The estimated impact is <b>{i} thousand USD per month</b> ({how}).","L’impact estimé est de <b>{i} k USD par mois</b> ({how}).","O impacto estimado é de <b>{i} mil USD por mês</b> ({how}).");
A('a.how.opex',"sobre lo esperado en el mes","above what was expected in the month","au-dessus de l’attendu dans le mois","acima do esperado no mês");
A('a.how.emis',"valuado al precio interno del carbono de {p} USD/t","valued at the internal carbon price of {p} USD/t","valorisé au prix interne du carbone de {p} USD/t","valorado ao preço interno do carbono de {p} USD/t");
A('a.how.prod',"valuado con netback de {p} USD/bbl","valued at a netback of {p} USD/bbl","valorisé avec un netback de {p} USD/bbl","valorado com netback de {p} USD/bbl");
A('a.r3c',"No hace falta actuar: se vigila de manera continua y el Vigía avisa si el desvío supera {l} σ durante varios períodos.","No action is needed: it is monitored continuously and the Watcher alerts if the deviation exceeds {l} σ for several periods.","Pas besoin d’agir : la surveillance est continue et la Vigie alerte si l’écart dépasse {l} σ sur plusieurs périodes.","Não é preciso agir: o monitoramento é contínuo e o Vigia avisa se o desvio superar {l} σ por vários períodos.");

/* ---- decisión ---- */
A('a.defact',"Revisar las causas del desvío con el responsable del campo.","Review the causes of the deviation with the field manager.","Examiner les causes de l’écart avec le responsable du champ.","Revisar as causas do desvio com o responsável pelo campo.");
A('a.du',"mil USD por mes en riesgo","k USD per month at risk","k USD par mois en jeu","mil USD por mês em risco");
A('a.dcap',"Desde {d} lleva {p} {u} fuera de lo esperado.","Since {d} it has been outside what is expected for {p} {u}.","Depuis {d}, cela fait {p} {u} hors de l’attendu.","Desde {d} está há {p} {u} fora do esperado.");
A('a.dg1p',"Recuperable: <b>hasta {g} bopd</b> si se corrige la causa.","Recoverable: <b>up to {g} bopd</b> if the cause is fixed.","Récupérable : <b>jusqu’à {g} bopd</b> si la cause est corrigée.","Recuperável: <b>até {g} bopd</b> se a causa for corrigida.");
A('a.dg1o',"Corregir la causa lleva el valor de vuelta a <b>{v} {u}</b>.","Fixing the cause brings the value back to <b>{v} {u}</b>.","Corriger la cause ramène la valeur à <b>{v} {u}</b>.","Corrigir a causa leva o valor de volta a <b>{v} {u}</b>.");
A('a.dg2',"Fuente de la acción: <b>{id}</b>. Queda registro de datos, fuentes y versión del cálculo.","Source of the action: <b>{id}</b>. Data, sources and calculation version are recorded.","Source de l’action : <b>{id}</b>. Données, sources et version du calcul sont consignées.","Fonte da ação: <b>{id}</b>. Ficam registrados dados, fontes e versão do cálculo.");
A('a.nwhat',"Seguir con la vigilancia. No se detecta una causa que justifique una intervención.","Keep monitoring. No cause is detected that justifies an intervention.","Poursuivre la surveillance. Aucune cause justifiant une intervention n’est détectée.","Seguir com o monitoramento. Não se detecta causa que justifique uma intervenção.");
A('a.nu',"% contra el período previo","% against the previous period","% par rapport à la période précédente","% em relação ao período anterior");
A('a.ncap',"El Vigía vuelve a revisar cuando entren nuevos datos.","The Watcher reviews again when new data arrives.","La Vigie revérifie à l’arrivée de nouvelles données.","O Vigia revisa novamente quando entrarem novos dados.");
A('a.ng1',"Sin impacto económico estimado.","No estimated economic impact.","Aucun impact économique estimé.","Sem impacto econômico estimado.");
A('a.ng2',"Para decidir sobre inversiones, abra el tablero {b}.","To decide on investments, open the {b} board.","Pour décider des investissements, ouvrez le tableau {b}.","Para decidir sobre investimentos, abra o painel {b}.");
A('a.dh1',"Acción que sugiere el tablero","Action the board suggests","Action suggérée par le tableau","Ação que o painel sugere");
A('a.dh2',"Conclusión del tablero","Board conclusion","Conclusion du tableau","Conclusão do painel");
A('a.bok1',"Enviar a aprobación","Send for approval","Envoyer pour approbation","Enviar para aprovação");
A('a.bok2',"Registrar revisión","Log review","Consigner la revue","Registrar revisão");
A('a.bokd1',"Enviado a aprobación","Sent for approval","Envoyé pour approbation","Enviado para aprovação");
A('a.bokd2',"Revisión registrada","Review logged","Revue consignée","Revisão registrada");
A('a.bgo',"Ver el tablero {b}","See the {b} board","Voir le tableau {b}","Ver o painel {b}");
A('a.note',"Datos de demostración. Una persona aprueba; los agentes no ejecutan cambios.","Demo data. A person approves; the agents do not execute changes.","Données de démonstration. Une personne approuve ; les agents n’exécutent aucun changement.","Dados de demonstração. Uma pessoa aprova; os agentes não executam mudanças.");
A('a.logged',"Registro (demo): fecha {d}, datos y fuentes usados, versión del cálculo y responsable.","Record (demo): date {d}, data and sources used, calculation version and owner.","Registre (démo) : date {d}, données et sources utilisées, version du calcul et responsable.","Registro (demo): data {d}, dados e fontes usados, versão do cálculo e responsável.");
A('a.srcs',"Fuentes consultadas","Sources consulted","Sources consultées","Fontes consultadas");
A('a.q',"¿Qué pasó con {nm} en {f}?","What happened with {nm} in {f}?","Que s’est-il passé avec {nm} à {f} ?","O que aconteceu com {nm} em {f}?");
A('a.autoT',"Anomalía detectada: {nm} en {f}","Anomaly detected: {nm} in {f}","Anomalie détectée : {nm} à {f}","Anomalia detectada: {nm} em {f}");
A('a.noscan',"No se detectaron anomalías en producción, costos ni emisiones.","No anomalies were detected in production, costs or emissions.","Aucune anomalie détectée en production, coûts ou émissions.","Não foram detectadas anomalias em produção, custos nem emissões.");
A('a.other',"Esa consulta se resuelve en el tablero <b>{b}</b>. Lo abro más abajo.","That question is answered on the <b>{b}</b> board. I open it below.","Cette question se résout dans le tableau <b>{b}</b>. Je l’ouvre plus bas.","Essa pergunta se resolve no painel <b>{b}</b>. Eu o abro mais abaixo.");
A('a.unk',"No pude identificar qué quiere verificar. Pruebe con la <b>producción</b>, los <b>costos</b> o las <b>emisiones</b> de un campo ({fields}), o con «{scan}».","I could not tell what you want to check. Try the <b>production</b>, <b>costs</b> or <b>emissions</b> of a field ({fields}), or “{scan}”.","Je n’ai pas pu identifier ce que vous voulez vérifier. Essayez la <b>production</b>, les <b>coûts</b> ou les <b>émissions</b> d’un champ ({fields}), ou « {scan} ».","Não consegui identificar o que quer verificar. Tente a <b>produção</b>, os <b>custos</b> ou as <b>emissões</b> de um campo ({fields}), ou «{scan}».");

/* ---- documentos de demostración ---- */
D('OP-014',["Respuesta a caídas de producción","Si un campo cae 10 % o más en 5 días sin cambio de choke, verificar primero la compresión y el suministro eléctrico, luego las bombas de fondo y los pozos con paradas. Priorizar las intervenciones con repago de 45 días o menos.","Verificar compresión y energía del campo y programar primero los pozos con repago de 45 días o menos."],["Response to production drops","If a field falls 10% or more in 5 days with no choke change, check compression and electrical supply first, then downhole pumps and shut-in wells. Prioritize interventions with a payback of 45 days or less.","Check field compression and power, and schedule first the wells with a payback of 45 days or less."],["Réponse aux baisses de production","Si un champ chute de 10 % ou plus en 5 jours sans changement de duse, vérifier d’abord la compression et l’alimentation électrique, puis les pompes de fond et les puits à l’arrêt. Prioriser les interventions dont le retour est de 45 jours ou moins.","Vérifier la compression et l’énergie du champ et programmer d’abord les puits dont le retour est de 45 jours ou moins."],["Resposta a quedas de produção","Se um campo cai 10% ou mais em 5 dias sem mudança de choke, verificar primeiro a compressão e o fornecimento elétrico, depois as bombas de fundo e os poços parados. Priorizar as intervenções com retorno de 45 dias ou menos.","Verificar a compressão e a energia do campo e programar primeiro os poços com retorno de 45 dias ou menos."]);
D('OP-021',["Pozos parados y bombas","Un pozo con una caída superior a 40 % entre dos controles se considera con falla de bomba o de energía hasta demostrar lo contrario. Se abre la orden de trabajo en 24 horas.","Abrir órdenes de trabajo en 24 horas para los pozos con caída mayor a 40 %."],["Shut-in wells and pumps","A well with a drop above 40% between two checks is considered a pump or power failure until proven otherwise. The work order is opened within 24 hours.","Open work orders within 24 hours for wells with a drop above 40%."],["Puits à l’arrêt et pompes","Un puits dont la baisse dépasse 40 % entre deux contrôles est considéré en panne de pompe ou d’énergie jusqu’à preuve du contraire. L’ordre de travail est ouvert sous 24 heures.","Ouvrir des ordres de travail sous 24 heures pour les puits dont la baisse dépasse 40 %."],["Poços parados e bombas","Um poço com queda superior a 40% entre duas verificações é considerado com falha de bomba ou de energia até prova em contrário. A ordem de serviço é aberta em 24 horas.","Abrir ordens de serviço em 24 horas para os poços com queda maior que 40%."]);
D('ING-007',["Declinación esperada (Arps)","La producción esperada se estima ajustando la declinación a los meses estables previos. Un desvío mayor a tres desviaciones estándar durante cinco días o más no se explica por la declinación natural del campo."],["Expected decline (Arps)","Expected production is estimated by fitting the decline to the previous stable months. A deviation above three standard deviations for five days or more is not explained by the field’s natural decline."],["Déclin attendu (Arps)","La production attendue est estimée en ajustant le déclin sur les mois stables précédents. Un écart supérieur à trois écarts-types pendant cinq jours ou plus ne s’explique pas par le déclin naturel du champ."],["Declínio esperado (Arps)","A produção esperada é estimada ajustando o declínio aos meses estáveis anteriores. Um desvio maior que três desvios-padrão por cinco dias ou mais não se explica pelo declínio natural do campo."]);
D('OP-033',["Compresión de gas","Una restricción de compresión reduce la producción de gas asociado y puede obligar a cerrar pozos con alta relación gas-petróleo. Revisar la disponibilidad de los compresores."],["Gas compression","A compression constraint reduces associated gas production and may force the shut-in of wells with a high gas-oil ratio. Check compressor availability."],["Compression de gaz","Une restriction de compression réduit la production de gaz associé et peut obliger à fermer des puits à fort rapport gaz-pétrole. Vérifier la disponibilité des compresseurs."],["Compressão de gás","Uma restrição de compressão reduz a produção de gás associado e pode obrigar a fechar poços com alta razão gás-óleo. Verificar a disponibilidade dos compressores."]);
D('FIN-012',["Control de costos operativos","Un gasto mensual de campo que supera 15 % lo esperado durante dos meses seguidos exige revisar contratos y consumo de energía antes del cierre siguiente.","Revisar los contratos de servicio y el consumo de energía del campo antes del próximo cierre mensual."],["Operating cost control","A field monthly spend that exceeds expectations by 15% for two months in a row requires a review of contracts and energy consumption before the next close.","Review the field’s service contracts and energy consumption before the next monthly close."],["Contrôle des coûts d’exploitation","Une dépense mensuelle de champ dépassant de 15 % le niveau attendu pendant deux mois consécutifs impose de revoir les contrats et la consommation d’énergie avant la clôture suivante.","Revoir les contrats de service et la consommation d’énergie du champ avant la prochaine clôture mensuelle."],["Controle de custos operacionais","Um gasto mensal de campo que supera em 15% o esperado por dois meses seguidos exige revisar contratos e consumo de energia antes do fechamento seguinte.","Revisar os contratos de serviço e o consumo de energia do campo antes do próximo fechamento mensal."]);
D('FIN-019',["Contratos de servicio","Los contratos con ajuste por indexación se revisan cada trimestre. Los desvíos suelen venir de tarifas por día de equipo y de horas extra."],["Service contracts","Contracts with indexation adjustment are reviewed every quarter. Variances usually come from rig-day rates and overtime."],["Contrats de service","Les contrats avec clause d’indexation sont revus chaque trimestre. Les écarts viennent généralement des tarifs par jour d’équipement et des heures supplémentaires."],["Contratos de serviço","Os contratos com reajuste por indexação são revisados a cada trimestre. Os desvios costumam vir de tarifas por dia de equipamento e de horas extras."]);
D('FIN-021',["Energía en campo","El consumo eléctrico del bombeo es la mayor parte del gasto de energía. Ajustar horarios y revisar equipos de bombeo sobredimensionados reduce el costo."],["Field energy","Electric consumption of pumping is most of the energy spend. Adjusting schedules and reviewing oversized pumping equipment reduces cost."],["Énergie sur les champs","La consommation électrique du pompage représente l’essentiel de la dépense d’énergie. Ajuster les horaires et revoir les équipements de pompage surdimensionnés réduit le coût."],["Energia em campo","O consumo elétrico do bombeamento é a maior parte do gasto de energia. Ajustar horários e revisar equipamentos de bombeamento superdimensionados reduz o custo."]);
D('AMB-004',["Venteo y quema","Un aumento sostenido de emisiones de más de 10 % en un campo se atribuye primero a venteo o quema por falla de compresión o de recuperación de gas.","Revisar la recuperación de gas de venteo y las fugas de metano (LDAR) del campo."],["Venting and flaring","A sustained emissions increase of more than 10% in a field is first attributed to venting or flaring from compression or gas-recovery failure.","Review the field’s vented-gas recovery and methane leaks (LDAR)."],["Évents et torchage","Une hausse soutenue des émissions de plus de 10 % sur un champ est d’abord attribuée aux évents ou au torchage par défaillance de la compression ou de la récupération du gaz.","Revoir la récupération du gaz des évents et les fuites de méthane (LDAR) du champ."],["Ventilação e queima","Um aumento sustentado de emissões de mais de 10% em um campo é atribuído primeiro à ventilação ou queima por falha de compressão ou de recuperação de gás.","Revisar a recuperação de gás de ventilação e os vazamentos de metano (LDAR) do campo."]);
D('AMB-009',["Detección y reparación de fugas","Los programas de detección y reparación de fugas reducen emisiones de metano con costo negativo. Se recomienda una campaña de inspección cuando hay desvíos."],["Leak detection and repair","Leak detection and repair programs reduce methane emissions at negative cost. An inspection campaign is recommended when deviations appear."],["Détection et réparation des fuites","Les programmes de détection et réparation des fuites réduisent les émissions de méthane à coût négatif. Une campagne d’inspection est recommandée en cas d’écarts."],["Detecção e reparo de vazamentos","Os programas de detecção e reparo de vazamentos reduzem emissões de metano com custo negativo. Recomenda-se uma campanha de inspeção quando há desvios."]);
D('AMB-012',["Precio interno del carbono","Para evaluar medidas de reducción se usa un precio interno de 45 USD por tonelada de CO₂e."],["Internal carbon price","To assess reduction measures, an internal price of 45 USD per tonne of CO₂e is used."],["Prix interne du carbone","Pour évaluer les mesures de réduction, on utilise un prix interne de 45 USD par tonne de CO₂e."],["Preço interno do carbono","Para avaliar medidas de redução usa-se um preço interno de 45 USD por tonelada de CO₂e."]);
D('RES-003',["Clasificación de reservas","Las reservas 1P, 2P y 3P son volúmenes comercialmente recuperables con distinto grado de certeza. Los recursos contingentes pasan a reservas cuando se cumplen sus condiciones, entre ellas la decisión de inversión."],["Reserves classification","1P, 2P and 3P reserves are commercially recoverable volumes with different degrees of certainty. Contingent resources become reserves when their conditions are met, including the investment decision."],["Classification des réserves","Les réserves 1P, 2P et 3P sont des volumes commercialement récupérables avec différents degrés de certitude. Les ressources contingentes deviennent des réserves lorsque leurs conditions sont remplies, dont la décision d’investissement."],["Classificação de reservas","As reservas 1P, 2P e 3P são volumes comercialmente recuperáveis com diferentes graus de certeza. Os recursos contingentes passam a reservas quando suas condições são cumpridas, entre elas a decisão de investimento."]);
D('RES-008',["Revisión por caída de producción","Una caída persistente de producción se evalúa antes del cierre anual de reservas, porque puede cambiar la declinación usada en las reservas 2P."],["Review after a production drop","A persistent production drop is assessed before the annual reserves close, because it can change the decline used in 2P reserves."],["Revue après une baisse de production","Une baisse persistante de production est évaluée avant la clôture annuelle des réserves, car elle peut modifier le déclin utilisé dans les réserves 2P."],["Revisão por queda de produção","Uma queda persistente de produção é avaliada antes do fechamento anual de reservas, pois pode alterar o declínio usado nas reservas 2P."]);
D('INV-002',["Criterio de inversión","Los proyectos se ordenan por valor presente neto dividido por capex y se financian en ese orden hasta agotar el presupuesto."],["Investment criterion","Projects are ranked by net present value divided by capex and funded in that order until the budget runs out."],["Critère d’investissement","Les projets sont classés par valeur actuelle nette divisée par le capex et financés dans cet ordre jusqu’à épuisement du budget."],["Critério de investimento","Os projetos são ordenados por valor presente líquido dividido pelo capex e financiados nessa ordem até esgotar o orçamento."]);
D('GOB-001',["Aprobación y registro","Toda recomendación requiere aprobación humana y deja registro de la fecha, los datos, las fuentes y la versión del cálculo."],["Approval and record","Every recommendation requires human approval and leaves a record of the date, the data, the sources and the calculation version."],["Approbation et registre","Toute recommandation requiert une approbation humaine et laisse une trace de la date, des données, des sources et de la version du calcul."],["Aprovação e registro","Toda recomendação exige aprovação humana e deixa registro da data, dos dados, das fontes e da versão do cálculo."]);

/* ---- impulso de búsqueda por tema (se suma a la consulta antes de recuperar) ---- */
A('a.boost.prod',"producción caída pozos compresión bombas declinación","production drop wells compression pumps decline","production baisse puits compression pompes déclin","produção queda poços compressão bombas declínio");
A('a.boost.opex',"costo gasto contratos energía","cost spend contracts energy","coût dépense contrats énergie","custo gasto contratos energia");
A('a.boost.emis',"emisiones venteo fugas metano carbono","emissions venting leaks methane carbon","émissions évents fuites méthane carbone","emissões ventilação vazamentos metano carbono");
A('a.boost.an',"desvío anomalía","deviation anomaly","écart anomalie","desvio anomalia");

['es','en','fr','pt'].forEach(function(l){H3L.add(l,o[l])});
})();
