(function(){var A=H3L.add;
A('es',{'i.title':'H3L Global Energy — Upstream Oil & Gas & Energy Transition','i.desc':'Plataforma de ingeniería y data science para la industria energética: reservas SPE-PRMS, quality control, transición energética, analítica y evaluación de proyectos.',
'i.sub':'Plataforma de ingeniería y data science para la industria energética.','i.kpi':'40 calculadoras certificadas &nbsp;·&nbsp; 32 agentes IA &nbsp;·&nbsp; 87 apps de QC','i.c1':'Explorar calculadoras','i.c2':'Ver dashboard','i.v2':'VERSIÓN 2 ·','i.cur':'Ir al sitio actual','i.hero':'Pronóstico de producción: gráfico de analítica junto a un bombeo mecánico al atardecer',
'i.lhead':'QUICKLOOK DE SERVICIOS','i.foot1':'Desarrollado por Leandro Collell','i.foot2':'Ingeniería · Data Science · Transición energética',
's1.lab':'Reservas','s1.cap':'01 · RESERVAS · CLASIFICACIÓN SPE-PRMS','s1.st':'Cargando módulo de reservas',
's2.lab':'Quality control de ingeniería de desarrollo','s2.cap':'02 · QUALITY CONTROL DE INGENIERÍA DE DESARROLLO','s2.st':'Validando controles de calidad de ingeniería',
's3.lab':'Transición Energética','s3.cap':'03 · TRANSICIÓN ENERGÉTICA','s3.st':'Cargando indicadores de transición energética',
's4.lab':'Analítica y simulación numérica','s4.cap':'04 · ANALÍTICA Y SIMULACIÓN NUMÉRICA','s4.st':'Inicializando analítica y simulación numérica',
's5.lab':'Evaluación de proyectos upstream','s5.cap':'05 · EVALUACIÓN DE PROYECTOS UPSTREAM','s5.st':'Evaluando proyectos upstream',
's6.lab':'Informes ejecutivos','s6.cap':'06 · INFORMES EJECUTIVOS','s6.st':'Compilando informes ejecutivos',
'i.done':'Listo','i.loading':'Cargando','i.queue':'En cola','i.ready':'Plataforma lista','i.mod':'MÓDULO {n} DE 6','i.modEnd':'6 DE 6 · COMPLETO',
'i.sndOn':'SONIDO: SÍ','i.sndOff':'SONIDO: NO','i.sndAct':'ACTIVAR SONIDO','i.skip':'OMITIR ›','i.gAria':'Entrar al sitio','i.gYes':'ENTRAR CON SONIDO','i.gNo':'ENTRAR SIN SONIDO',
'sc.unc':'Incertidumbre  P90 · P50 · P10','sc.p1':'1P · Probadas','sc.p2':'2P · Probables','sc.p3':'3P · Posibles','sc.ucl':'LSC','sc.mean':'Media','sc.lcl':'LIC','sc.dev':'Desvío detectado','sc.ctl':'Dentro de control','sc.cross':'Punto de cruce','sc.emis':'Emisiones','sc.low':'Energía de bajo carbono','sc.lp':'Presión baja','sc.hp':'alta','sc.grid':'Malla 24 × 12','sc.cf':'Flujo acumulado','sc.npv':'VAN','sc.irr':'TIR','sc.rep':'Informe ejecutivo','sc.card':'ANALÍTICA · PRODUCCIÓN','sc.hist':'Histórico','sc.fc':'Pronóstico'});
A('en',{'i.title':'H3L Global Energy — Upstream Oil & Gas & Energy Transition','i.desc':'Engineering and data science platform for the energy industry: SPE-PRMS reserves, quality control, energy transition, analytics and project evaluation.',
'i.sub':'Engineering and data science platform for the energy industry.','i.kpi':'40 certified calculators &nbsp;·&nbsp; 32 AI agents &nbsp;·&nbsp; 87 QC apps','i.c1':'Explore calculators','i.c2':'View dashboards','i.v2':'VERSION 2 ·','i.cur':'Go to the current site','i.hero':'Production forecast: analytics chart next to a pumpjack at sunset',
'i.lhead':'SERVICES QUICKLOOK','i.foot1':'Developed by Leandro Collell','i.foot2':'Engineering · Data Science · Energy transition',
's1.lab':'Reserves','s1.cap':'01 · RESERVES · SPE-PRMS CLASSIFICATION','s1.st':'Loading reserves module',
's2.lab':'Development engineering quality control','s2.cap':'02 · DEVELOPMENT ENGINEERING QUALITY CONTROL','s2.st':'Validating engineering quality controls',
's3.lab':'Energy transition','s3.cap':'03 · ENERGY TRANSITION','s3.st':'Loading energy transition indicators',
's4.lab':'Analytics and numerical simulation','s4.cap':'04 · ANALYTICS AND NUMERICAL SIMULATION','s4.st':'Initializing analytics and numerical simulation',
's5.lab':'Upstream project evaluation','s5.cap':'05 · UPSTREAM PROJECT EVALUATION','s5.st':'Evaluating upstream projects',
's6.lab':'Executive reports','s6.cap':'06 · EXECUTIVE REPORTS','s6.st':'Compiling executive reports',
'i.done':'Ready','i.loading':'Loading','i.queue':'Queued','i.ready':'Platform ready','i.mod':'MODULE {n} OF 6','i.modEnd':'6 OF 6 · COMPLETE',
'i.sndOn':'SOUND: ON','i.sndOff':'SOUND: OFF','i.sndAct':'ENABLE SOUND','i.skip':'SKIP ›','i.gAria':'Enter the site','i.gYes':'ENTER WITH SOUND','i.gNo':'ENTER WITHOUT SOUND',
'sc.unc':'Uncertainty  P90 · P50 · P10','sc.p1':'1P · Proved','sc.p2':'2P · Probable','sc.p3':'3P · Possible','sc.ucl':'UCL','sc.mean':'Mean','sc.lcl':'LCL','sc.dev':'Deviation detected','sc.ctl':'In control','sc.cross':'Crossover point','sc.emis':'Emissions','sc.low':'Low-carbon energy','sc.lp':'Low pressure','sc.hp':'high','sc.grid':'Grid 24 × 12','sc.cf':'Cumulative cash flow','sc.npv':'NPV','sc.irr':'IRR','sc.rep':'Executive report','sc.card':'ANALYTICS · PRODUCTION','sc.hist':'Historical','sc.fc':'Forecast'});
A('fr',{'i.title':'H3L Global Energy — Upstream Oil & Gas & Energy Transition','i.desc':"Plateforme d'ingénierie et de data science pour l'industrie énergétique : réserves SPE-PRMS, contrôle qualité, transition énergétique, analytique et évaluation de projets.",
'i.sub':"Plateforme d'ingénierie et de data science pour l'industrie énergétique.",'i.kpi':'40 calculateurs certifiés &nbsp;·&nbsp; 32 agents IA &nbsp;·&nbsp; 87 apps QC','i.c1':'Explorer les calculateurs','i.c2':'Voir les tableaux de bord','i.v2':'VERSION 2 ·','i.cur':'Aller au site actuel','i.hero':"Prévision de production : graphique analytique à côté d'une pompe à balancier au coucher du soleil",
'i.lhead':'APERÇU DES SERVICES','i.foot1':'Développé par Leandro Collell','i.foot2':'Ingénierie · Data Science · Transition énergétique',
's1.lab':'Réserves','s1.cap':'01 · RÉSERVES · CLASSIFICATION SPE-PRMS','s1.st':'Chargement du module de réserves',
's2.lab':"Contrôle qualité de l'ingénierie de développement",'s2.cap':"02 · CONTRÔLE QUALITÉ DE L'INGÉNIERIE DE DÉVELOPPEMENT",'s2.st':"Validation des contrôles qualité de l'ingénierie",
's3.lab':'Transition énergétique','s3.cap':'03 · TRANSITION ÉNERGÉTIQUE','s3.st':'Chargement des indicateurs de transition énergétique',
's4.lab':'Analytique et simulation numérique','s4.cap':'04 · ANALYTIQUE ET SIMULATION NUMÉRIQUE','s4.st':"Initialisation de l'analytique et de la simulation numérique",
's5.lab':'Évaluation de projets amont','s5.cap':'05 · ÉVALUATION DE PROJETS AMONT','s5.st':'Évaluation des projets amont',
's6.lab':'Rapports exécutifs','s6.cap':'06 · RAPPORTS EXÉCUTIFS','s6.st':'Compilation des rapports exécutifs',
'i.done':'Prêt','i.loading':'Chargement','i.queue':'En attente','i.ready':'Plateforme prête','i.mod':'MODULE {n} SUR 6','i.modEnd':'6 SUR 6 · TERMINÉ',
'i.sndOn':'SON : OUI','i.sndOff':'SON : NON','i.sndAct':'ACTIVER LE SON','i.skip':'PASSER ›','i.gAria':'Entrer sur le site','i.gYes':'ENTRER AVEC LE SON','i.gNo':'ENTRER SANS LE SON',
'sc.unc':'Incertitude  P90 · P50 · P10','sc.p1':'1P · Prouvées','sc.p2':'2P · Probables','sc.p3':'3P · Possibles','sc.ucl':'LSC','sc.mean':'Moyenne','sc.lcl':'LIC','sc.dev':'Écart détecté','sc.ctl':'Sous contrôle','sc.cross':'Point de croisement','sc.emis':'Émissions','sc.low':'Énergie bas carbone','sc.lp':'Pression basse','sc.hp':'haute','sc.grid':'Maillage 24 × 12','sc.cf':'Flux cumulé','sc.npv':'VAN','sc.irr':'TRI','sc.rep':'Rapport exécutif','sc.card':'ANALYTIQUE · PRODUCTION','sc.hist':'Historique','sc.fc':'Prévision'});
A('pt',{'i.title':'H3L Global Energy — Upstream Oil & Gas & Energy Transition','i.desc':'Plataforma de engenharia e data science para a indústria de energia: reservas SPE-PRMS, controle de qualidade, transição energética, analítica e avaliação de projetos.',
'i.sub':'Plataforma de engenharia e data science para a indústria de energia.','i.kpi':'40 calculadoras certificadas &nbsp;·&nbsp; 32 agentes de IA &nbsp;·&nbsp; 87 apps de QC','i.c1':'Explorar calculadoras','i.c2':'Ver painéis','i.v2':'VERSÃO 2 ·','i.cur':'Ir para o site atual','i.hero':'Previsão de produção: gráfico de analítica ao lado de uma bomba de cavalete ao entardecer',
'i.lhead':'VISÃO RÁPIDA DOS SERVIÇOS','i.foot1':'Desenvolvido por Leandro Collell','i.foot2':'Engenharia · Data Science · Transição energética',
's1.lab':'Reservas','s1.cap':'01 · RESERVAS · CLASSIFICAÇÃO SPE-PRMS','s1.st':'Carregando módulo de reservas',
's2.lab':'Controle de qualidade da engenharia de desenvolvimento','s2.cap':'02 · CONTROLE DE QUALIDADE DA ENGENHARIA DE DESENVOLVIMENTO','s2.st':'Validando controles de qualidade da engenharia',
's3.lab':'Transição energética','s3.cap':'03 · TRANSIÇÃO ENERGÉTICA','s3.st':'Carregando indicadores de transição energética',
's4.lab':'Analítica e simulação numérica','s4.cap':'04 · ANALÍTICA E SIMULAÇÃO NUMÉRICA','s4.st':'Inicializando analítica e simulação numérica',
's5.lab':'Avaliação de projetos upstream','s5.cap':'05 · AVALIAÇÃO DE PROJETOS UPSTREAM','s5.st':'Avaliando projetos upstream',
's6.lab':'Relatórios executivos','s6.cap':'06 · RELATÓRIOS EXECUTIVOS','s6.st':'Compilando relatórios executivos',
'i.done':'Pronto','i.loading':'Carregando','i.queue':'Na fila','i.ready':'Plataforma pronta','i.mod':'MÓDULO {n} DE 6','i.modEnd':'6 DE 6 · COMPLETO',
'i.sndOn':'SOM: SIM','i.sndOff':'SOM: NÃO','i.sndAct':'ATIVAR SOM','i.skip':'PULAR ›','i.gAria':'Entrar no site','i.gYes':'ENTRAR COM SOM','i.gNo':'ENTRAR SEM SOM',
'sc.unc':'Incerteza  P90 · P50 · P10','sc.p1':'1P · Provadas','sc.p2':'2P · Prováveis','sc.p3':'3P · Possíveis','sc.ucl':'LSC','sc.mean':'Média','sc.lcl':'LIC','sc.dev':'Desvio detectado','sc.ctl':'Sob controle','sc.cross':'Ponto de cruzamento','sc.emis':'Emissões','sc.low':'Energia de baixo carbono','sc.lp':'Pressão baixa','sc.hp':'alta','sc.grid':'Malha 24 × 12','sc.cf':'Fluxo acumulado','sc.npv':'VPL','sc.irr':'TIR','sc.rep':'Relatório executivo','sc.card':'ANALÍTICA · PRODUÇÃO','sc.hist':'Histórico','sc.fc':'Previsão'});
})();
